// <auto-generated />
namespace StationLinerDataEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users_view : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_view));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200950273_users_view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
